# Generated by Django 5.2.6 on 2025-09-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram',
            name='pin_required',
            field=models.BooleanField(default=False),
        ),
    ]
