# Generated by Django 5.2.6 on 2025-09-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_telegram_pin_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
