# Generated by Django 5.2.6 on 2025-09-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_contact_telegram_user_id_contact_telegram_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='telegram_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
