# Generated by Django 5.2.6 on 2025-09-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmessage_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='replied',
            new_name='user_approved_reply',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_sent',
            field=models.BooleanField(default=False),
        ),
    ]
