# Generated by Django 5.2.6 on 2025-09-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_reply_emotion_and_more'),
        ('chat', '0005_rename_replied_chatmessage_user_approved_reply_and_more'),
    ]

    operations = [
    ]
