# Generated by Django 5.2.6 on 2025-09-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_chatmessage_reply_emotion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
